// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/course_category.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	proto/course_category.proto

It has these top-level messages:
	Blank
	Category
	CategoryResponse
	CreateCategoryRequest
	CategoryList
	GetCategoryRequest
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blank struct {
}

func (m *Blank) Reset()                    { *m = Blank{} }
func (m *Blank) String() string            { return proto.CompactTextString(m) }
func (*Blank) ProtoMessage()               {}
func (*Blank) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Category struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
}

func (m *Category) Reset()                    { *m = Category{} }
func (m *Category) String() string            { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()               {}
func (*Category) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Category) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CategoryResponse struct {
	Category *Category `protobuf:"bytes,1,opt,name=category" json:"category,omitempty"`
}

func (m *CategoryResponse) Reset()                    { *m = CategoryResponse{} }
func (m *CategoryResponse) String() string            { return proto.CompactTextString(m) }
func (*CategoryResponse) ProtoMessage()               {}
func (*CategoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CategoryResponse) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

type CreateCategoryRequest struct {
	Name        string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *CreateCategoryRequest) Reset()                    { *m = CreateCategoryRequest{} }
func (m *CreateCategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateCategoryRequest) ProtoMessage()               {}
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateCategoryRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCategoryRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CategoryList struct {
	Categories []*Category `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
}

func (m *CategoryList) Reset()                    { *m = CategoryList{} }
func (m *CategoryList) String() string            { return proto.CompactTextString(m) }
func (*CategoryList) ProtoMessage()               {}
func (*CategoryList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CategoryList) GetCategories() []*Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type GetCategoryRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetCategoryRequest) Reset()                    { *m = GetCategoryRequest{} }
func (m *GetCategoryRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCategoryRequest) ProtoMessage()               {}
func (*GetCategoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetCategoryRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Blank)(nil), "pb.Blank")
	proto.RegisterType((*Category)(nil), "pb.Category")
	proto.RegisterType((*CategoryResponse)(nil), "pb.CategoryResponse")
	proto.RegisterType((*CreateCategoryRequest)(nil), "pb.CreateCategoryRequest")
	proto.RegisterType((*CategoryList)(nil), "pb.CategoryList")
	proto.RegisterType((*GetCategoryRequest)(nil), "pb.GetCategoryRequest")
}

func init() { proto.RegisterFile("proto/course_category.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4f, 0x3a, 0x31,
	0x10, 0xc5, 0xe9, 0xf2, 0xfd, 0x2a, 0xcc, 0x22, 0x92, 0x89, 0x9a, 0x55, 0x2f, 0xa4, 0xf1, 0xc0,
	0xc1, 0x40, 0x82, 0xf1, 0xa4, 0x27, 0x38, 0x70, 0xd1, 0xc4, 0xc0, 0xcd, 0x8b, 0xe9, 0x2e, 0x13,
	0xd3, 0x08, 0x6d, 0x6d, 0x8b, 0x89, 0x7f, 0xbd, 0x66, 0x1b, 0x76, 0x5d, 0x7e, 0xe8, 0xad, 0x99,
	0xf7, 0xf6, 0xf5, 0xf3, 0x66, 0x0b, 0x97, 0xc6, 0x6a, 0xaf, 0x07, 0x99, 0x5e, 0x59, 0x47, 0x2f,
	0x99, 0xf0, 0xf4, 0xaa, 0xed, 0x67, 0x3f, 0x4c, 0x31, 0x32, 0x29, 0x3f, 0x84, 0xff, 0xa3, 0x85,
	0x50, 0x6f, 0xfc, 0x09, 0x1a, 0xe3, 0xb5, 0x8c, 0x6d, 0x88, 0xe4, 0x3c, 0x61, 0x5d, 0xd6, 0x6b,
	0x4e, 0x23, 0x39, 0x47, 0x84, 0x7f, 0x4a, 0x2c, 0x29, 0x89, 0xc2, 0x24, 0x9c, 0xb1, 0x0b, 0xf1,
	0x9c, 0x5c, 0x66, 0xa5, 0xf1, 0x52, 0xab, 0xa4, 0x1e, 0xa4, 0xea, 0x88, 0xdf, 0x43, 0xa7, 0x48,
	0x9c, 0x92, 0x33, 0x5a, 0x39, 0xc2, 0x1e, 0x34, 0x0a, 0x88, 0x90, 0x1f, 0x0f, 0x5b, 0x7d, 0x93,
	0xf6, 0x4b, 0x5f, 0xa9, 0xf2, 0x47, 0x38, 0x1d, 0x5b, 0x12, 0x9e, 0x7e, 0x32, 0xde, 0x57, 0xe4,
	0x7c, 0x09, 0xc3, 0x7e, 0x87, 0x89, 0xf6, 0xc1, 0xb4, 0x8a, 0xa0, 0x07, 0xe9, 0x3c, 0x5e, 0x03,
	0xac, 0xaf, 0x92, 0xe4, 0x12, 0xd6, 0xad, 0xef, 0xa0, 0x54, 0x74, 0x7e, 0x05, 0x38, 0x21, 0xbf,
	0x4d, 0xb2, 0xb5, 0xa6, 0xe1, 0x17, 0x83, 0xe3, 0xc2, 0x33, 0x23, 0xfb, 0x21, 0x33, 0xc2, 0x3b,
	0x68, 0x6f, 0xd6, 0xc0, 0xf3, 0x70, 0xcb, 0xbe, 0x6a, 0x17, 0x1b, 0x00, 0xbc, 0x86, 0x13, 0x38,
	0xd9, 0x34, 0xce, 0xbc, 0x25, 0xb1, 0xfc, 0x2b, 0xa2, 0x53, 0x8d, 0xc8, 0x9b, 0xf2, 0x5a, 0x8f,
	0xe1, 0x00, 0xda, 0xf9, 0x79, 0x5c, 0x36, 0xc2, 0x66, 0xee, 0x0b, 0x7f, 0x7e, 0xdf, 0x27, 0x78,
	0x0b, 0x71, 0xa5, 0x30, 0x9e, 0xe5, 0x96, 0xdd, 0x0d, 0x6c, 0x03, 0x8f, 0x8e, 0x9e, 0x63, 0xa9,
	0x3c, 0x59, 0x25, 0x16, 0x03, 0x93, 0xa6, 0x07, 0xe1, 0x9d, 0xdd, 0x7c, 0x07, 0x00, 0x00, 0xff,
	0xff, 0x18, 0x90, 0x71, 0x38, 0x86, 0x02, 0x00, 0x00,
}
